spring.application.name=hrms
spring.datasource.url=jdbc:mysql://localhost:3306/dayflow_db
spring.datasource.username=root
spring.datasource.password=Sri@2006
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080